export type CommunityModerationAction =
  | 'channel_created'
  | 'channel_deleted'
  | 'channel_permissions_updated'
  | 'channel_renamed'
  | 'community_updated'
  | 'invitation_created'
  | 'invite_link_created'
  | 'member_banned'
  | 'member_roles_updated'
  | 'member_unbanned'
  | 'membership_request_accepted'
  | 'membership_request_declined'
  | 'message_deleted'
  | 'role_created'
  | 'role_deleted'
  | 'role_updated';
