import { KeyPair } from '@haskou/pigeon-swarm-crypto';

import type { Session } from '../../../../../shared/domain/pigeonResources.types';

import { ConversationOperationSigner } from '../../../../../contexts/conversations/infrastructure/http/ConversationOperationSigner';
import { PublicMutationSigner } from '../../../../../shared/infrastructure/crypto/PublicMutationSigner';
import vectors from '../../../../fixtures/conversation-operation-vectors.json';

// The fixture is generated by the node (ConversationId, ConversationOperation,
// PublicMutationProof): ed25519 is deterministic, so even signatures match.
type Vector = (typeof vectors.cases)[number];

function sessionOf(signer: keyof typeof vectors.keys): Session {
  const key = vectors.keys[signer];

  return {
    deviceCredentialKeyPair: KeyPair.fromPrimitives({
      privateKey: key.privateKeyPem,
      publicKey: key.publicKeyPem,
    } as never),
    identity: { id: key.identityId },
  } as unknown as Session;
}

describe(ConversationOperationSigner.name, () => {
  const signer = new ConversationOperationSigner();

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it.each(vectors.cases)(
    'signs $name byte for byte like the node',
    (vector: Vector) => {
      const { derived, input } = vector;

      jest
        .spyOn(PublicMutationSigner.prototype as never, 'operationId')
        .mockReturnValue(input.operationId as never);

      const operation = signer.sign(
        sessionOf(input.signer as keyof typeof vectors.keys),
        {
          action: input.action,
          args: input.args,
          conversationId: input.conversationId,
          createdAt: input.createdAt,
          networkId: input.networkId,
          parents: [...input.parents].reverse(),
        },
      );

      expect(operation).toEqual(derived.requestOperation);
      expect(operation.mutation.recordId).toBe(derived.recordId);
      expect(operation.mutation.payloadDigest).toBe(derived.payloadDigest);
    },
  );
});
