import type { CallPeerRecoveryState } from '../../infrastructure/media/CallPeerRecoveryState';
import type { IdentityResource } from '../../../../shared/domain/pigeonResources.types';

export type CallParticipant = {
  audioLevel?: number;
  bitrateKbps?: number;
  codec?: string;
  connectionPath?: 'direct' | 'relay' | 'unknown';
  connectionState?: RTCPeerConnectionState;
  connected?: boolean;
  deafened?: boolean;
  identity?: IdentityResource;
  identityId: string;
  iceState?: RTCIceConnectionState;
  jitterMs?: number;
  lastHeartbeatAt?: number;
  latencyMs?: number;
  mediaEncryptionActive?: boolean;
  mediaStream?: MediaStream;
  muted: boolean;
  name: string;
  packetsLost?: number;
  recoveryState?: CallPeerRecoveryState;
  picture?: null | string;
  screenStream?: MediaStream;
  screenSharing?: boolean;
  speaking?: boolean;
  status?: 'declined' | 'joined' | 'left' | 'missed' | 'ringing';
  transport?: string;
  videoEnabled?: boolean;
};
