import { KeyPair } from '@haskou/pigeon-swarm-crypto';

import type { Session } from '../../../../../shared/domain/pigeonResources.types';

import { CallEventSigner } from '../../../../../contexts/calls/infrastructure/http/CallEventSigner';
import { PublicMutationSigner } from '../../../../../shared/infrastructure/crypto/PublicMutationSigner';
import vectors from '../../../../fixtures/call-event-vectors.json';

// The fixture is generated by the node (CallId.fromStart, PublicMutationProof):
// ed25519 is deterministic, so even signatures must match byte for byte.
type Vector = (typeof vectors.cases)[number];
type Payload = Record<string, unknown>;

function sessionOf(
  key: (typeof vectors.keys)[keyof typeof vectors.keys],
): Session {
  return {
    deviceCredentialKeyPair: KeyPair.fromPrimitives({
      privateKey: key.privateKeyPem,
      publicKey: key.publicKeyPem,
    } as never),
    identity: { id: key.identityId },
  } as unknown as Session;
}

function vector(name: string): Vector['derived'] {
  return vectors.cases.find((candidate) => candidate.name === name)!.derived;
}

describe(CallEventSigner.name, () => {
  const signer = new CallEventSigner();
  const { callee, creator } = vectors.keys;

  function stubOperationId(mutation: { operationId: string }): void {
    jest
      .spyOn(PublicMutationSigner.prototype as never, 'operationId')
      .mockReturnValue(mutation.operationId as never);
  }

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it.each(
    vectors.cases.filter((candidate) => 'callIdPreimage' in candidate.derived),
  )('derives the call id of $name like the node', ({ derived }) => {
    const payload = derived.payload as Payload;

    expect(
      signer.callId(
        payload.creatorIdentityId as string,
        payload.nonce as string,
      ),
    ).toBe(payload.callId);
  });

  it('generates nonces accepted by the node', () => {
    expect(signer.nonce()).toMatch(/^[A-Za-z0-9_-]{16,128}$/);
  });

  it.each(['conversation_call_start', 'community_call_start'])(
    'signs %s byte for byte like the node',
    (name) => {
      const { mutation, payload } = vector(name) as unknown as {
        mutation: { operationId: string };
        payload: Payload & { scope: Payload & { type: string } };
      };
      const conversation = payload.scope.type === 'conversation';

      stubOperationId(mutation);

      const signed = signer.start(sessionOf(creator), {
        networkId: payload.networkId as string,
        nonce: payload.nonce as string,
        participantIds: [...(payload.participantIds as string[])].reverse(),
        scope: payload.scope as never,
        ...(conversation
          ? {}
          : { sessionEpoch: payload.sessionEpoch as number }),
        startedAt: payload.startedAt as number,
      });

      expect(signed.callId).toBe(payload.callId);
      expect(signed.mutation).toEqual(mutation);
    },
  );

  it('signs a participant state and its successor like the node', () => {
    const joined = vector('call_participant_joined');
    const left = vector('call_participant_left_after_joined');
    const session = sessionOf(callee);
    const joinedPayload = joined.payload as Payload;
    const leftPayload = left.payload as Payload;

    stubOperationId(joined.mutation);
    const first = signer.participant(
      session,
      joinedPayload.callId as string,
      'joined',
      joinedPayload.at as number,
      PublicMutationSigner.FIRST_POSITION,
    );

    expect(first).toEqual(joined.mutation);

    stubOperationId(left.mutation);
    const second = signer.participant(
      session,
      leftPayload.callId as string,
      'left',
      leftPayload.at as number,
      {
        predecessor: new PublicMutationSigner().digestOf(first),
        sequence: 1,
      },
    );

    expect(second).toEqual(left.mutation);
  });

  it('signs the call end like the node', () => {
    const end = vector('call_end');
    const payload = end.payload as Payload;

    stubOperationId(end.mutation);

    expect(
      signer.end(
        sessionOf(creator),
        payload.callId as string,
        payload.at as number,
      ),
    ).toEqual(end.mutation);
  });
});
