openapi: 3.0.3
info:
  title: Pigeon-swarm APIs
  version: 1.0.0
  description: Aggregated OpenAPI document built with references to each API file.
tags:
  - name: conversations
  - name: identities
  - name: ipfs
  - name: keychains
paths:
  /conversations:
    $ref: './conversations-api/swagger.yaml#/paths/~1conversations'
  /conversations/{conversationId}/messages:
    $ref: './conversations-api/swagger.yaml#/paths/~1conversations~1{conversationId}~1messages'
  /identities/:
    $ref: './identities-api/swagger.yaml#/paths/~1identities~1'
  /identities/{identityId}:
    $ref: './identities-api/swagger.yaml#/paths/~1identities~1{identityId}'
  /ipfs/{cid}:
    $ref: './ipfs.yaml#/paths/~1ipfs~1{cid}'
  /ipfs/replication/status:
    $ref: './ipfs.yaml#/paths/~1ipfs~1replication~1status'
  /keychains/:
    $ref: './keychains-api/swagger.yaml#/paths/~1keychains~1'
  /keychains/{identityId}:
    $ref: './keychains-api/swagger.yaml#/paths/~1keychains~1{identityId}'
