import { KeyPair } from '@haskou/pigeon-swarm-crypto';

import type { Session } from '../../../../../shared/domain/pigeonResources.types';

import { CommunityOperationSigner } from '../../../../../contexts/communities/infrastructure/http/CommunityOperationSigner';
import { deriveCommunityId } from '../../../../../contexts/communities/infrastructure/http/deriveCommunityRecordId';
import { PublicMutationSigner } from '../../../../../shared/infrastructure/crypto/PublicMutationSigner';
import vectors from '../../../../fixtures/community-operation-vectors.json';
import { publicMutationSignerAt } from '../../../../shared/infrastructure/crypto/publicMutationSignerAt';

// The fixture is generated by the node (CommunityId.derive, CommunityOperation,
// PublicMutationProof): ed25519 is deterministic, so even signatures match.
type Vector = (typeof vectors.cases)[number];

function sessionOf(signer: keyof typeof vectors.keys): Session {
  const key = vectors.keys[signer];

  return {
    deviceCredentialKeyPair: KeyPair.fromPrimitives({
      privateKey: key.privateKeyPem,
      publicKey: key.publicKeyPem,
    } as never),
    identity: { id: key.identityId },
  } as unknown as Session;
}

describe(CommunityOperationSigner.name, () => {
  const signer = new CommunityOperationSigner(publicMutationSignerAt());

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it.each(Object.entries(vectors.communities))(
    'derives the %s community id like the node',
    (_name, community) => {
      const preimage = JSON.parse(community.communityIdPreimage) as {
        networkId: string;
        nonce: string;
        ownerIdentityId: string;
      };

      expect(
        deriveCommunityId(
          preimage.networkId,
          preimage.ownerIdentityId,
          preimage.nonce,
        ),
      ).toBe(community.communityId);
    },
  );

  it.each(vectors.cases)(
    'signs $name byte for byte like the node',
    async (vector: Vector) => {
      const { derived, input } = vector;

      jest
        .spyOn(PublicMutationSigner.prototype as never, 'operationId')
        .mockReturnValue(input.operationId as never);

      const operation = await signer.sign(
        sessionOf(input.signer as keyof typeof vectors.keys),
        {
          action: input.action,
          args: input.args,
          communityId: input.communityId,
          createdAt: input.createdAt,
          networkId: input.networkId,
          parents: [...input.parents].reverse(),
        },
      );

      expect(operation).toEqual(derived.requestOperation);
      expect(operation.mutation.recordId).toBe(derived.recordId);
      expect(operation.mutation.payloadDigest).toBe(derived.payloadDigest);
    },
  );
});
